name: Test Build

on:
  push:
    branches: [ main, master, develop ]
    tags-ignore: [ '**' ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test-build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Test Windows build
      run: |
        pyinstaller app.spec --clean --noconfirm

    - name: Verify executable exists
      run: |
        if (Test-Path "dist\mailtime.exe") {
          Write-Host "✅ Windows executable built successfully"
          Get-Item "dist\mailtime.exe" | Select-Object Name, Length, LastWriteTime
        } else {
          Write-Host "❌ Windows executable not found"
          exit 1
        }

  test-build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxcb-xinerama0 libxcb-cursor0 libxkbcommon-x11-0

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Test Linux build
      env:
        QT_QPA_PLATFORM: offscreen
      run: |
        pyinstaller app.spec --clean --noconfirm

    - name: Verify executable exists
      run: |
        if [ -f "dist/mailtime" ]; then
          echo "✅ Linux executable built successfully"
          ls -la dist/mailtime
        else
          echo "❌ Linux executable not found"
          exit 1
        fi